In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df=pd.read_csv("train_dataset.csv")

In [33]:
df.shape

(150, 6)

In [34]:
df.sample(5)

,flow_rate_L_min,concentration_mol_L,inlet_temperature_K,length_m,jacket_temperature_K,overall_yield
69,79.02,3.47,360.40,5.46,407.02,10.824
139,77.88,2.57,362.20,5.49,425.39,11.622
114,52.51,3.57,444.78,10.06,419.77,85.630
11,77.74,2.71,361.77,16.93,509.88,67.250
19,26.84,2.57,387.54,24.15,499.65,0.000

In [35]:
x=df.iloc[:,:5]
y=df.iloc[:,-1]

In [36]:
x

,flow_rate_L_min,concentration_mol_L,inlet_temperature_K,length_m,jacket_temperature_K
0,33.09,3.68,357.75,19.87,383.79
1,76.30,1.34,429.70,14.84,405.72
2,59.90,1.01,431.10,11.76,385.40
3,49.90,2.21,445.61,22.85,367.74
4,16.70,3.95,458.91,4.56,374.13
...,...,...,...,...,...
145,7.77,2.33,492.09,12.90,529.91
146,50.72,3.19,497.90,17.35,426.78
147,42.70,1.26,463.01,5.96,458.71
148,8.86,2.68,406.44,6.42,531.29
149,25.90,0.80,362.53,2.94,474.85

In [37]:
y

0      63.024
1      86.611
2      86.347
3      92.175
4      82.211
        ...
145     0.000
146     1.249
147     0.645
148     0.000
149    28.516
Name: overall_yield, Length: 150, dtype: float64

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [39]:
#from sklearn.preprocessing import StandardScaler
#ss=StandardScaler()

In [40]:
#x_train=ss.fit_transform(x_train)
#x_test=ss.transform(x_test)

In [41]:
from catboost import CatBoostRegressor

cat = CatBoostRegressor(
    iterations=300,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    random_state=42,
    verbose=0
)

In [42]:
cat.fit(x_train, y_train)

CatBoostRegressor(depth=6, iterations=300, learning_rate=0.05, loss_function='RMSE', random_state=42, verbose=0)

In [43]:
results = cat.predict(x_test)

In [44]:
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    mean_absolute_percentage_error
)
print("R² Score :", r2_score(y_test, results))
print("MAE      :", mean_absolute_error(y_test, results))
print("MSE      :", mean_squared_error(y_test, results))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, results)))
print("MAPE     :", mean_absolute_percentage_error(y_test, results))

R² Score : 0.5255521971679047
MAE      : 19.162069483799545
MSE      : 575.7937473839517
RMSE     : 23.99570268577171
MAPE     : 2.3557916231585264e+16